name: Lint and App Inspect CLI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: lint

      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build

      - name: Update Version Number
        run: |
          old_str="X.Y.Z"
          new_str="1.0.0"
          sed -i "s/$old_str/$new_str/g" package.json
          sed -i "s/$old_str/$new_str/g" ./github_app_for_splunk/default/app.conf

      - name: Build Package
        run: COPYFILE_DISABLE=1 tar -cvzf package.tar.gz ./github_app_for_splunk

      - name: Run App Inspect CLI
        uses: splunk/appinspect-cli-action@v1
        with:
          app_path: package.tar.gz
          included_tags: cloud, splunk_appinspect
          
      - name: Send data to OTLP backend
        if: always()
        uses: codeboten/github-action-to-otlp@v1
        with:
          endpoint: "20.163.240.115:4317"
          
      - name: Export Workflow Trace
        if: always()
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: grpc://20.163.240.115:4317/
          otlpHeaders: "x-honeycomb-team=YOUR_API_KEY,x-honeycomb-dataset=YOUR_DATASET"
