name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name!='WriteLogs'}}
    steps:
      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: https://dev.erkkila.co:8088/services/collector/raw?token=f07eca1b-5cb3-4d33-85b9-4255a472809d
          otelServiceName: "GitHubWorkflows"
          githubToken: ${{ secrets.TOKEN_GITHUB }}
          runId: ${{ github.event.workflow_run.id }}
