name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name!='WriteLogs'}}
    steps:
      - name: Export Workflow Trace
        env:
          OTEL_CONSOLE_ONLY: false
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: http://20.163.240.115:9444/event1
          otelServiceName: "GitHubWorkflows"
          githubToken: ${{ secrets.TOKEN_GITHUB }}
          runId: ${{ github.event.workflow_run.id }}
