name: Send Workflow Logs to Splunk

# Controls when the action will run.
on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed

env:
  triggerID: ${{ github.event.workflow_run.id }}
  triggerJob: ${{ github.event.workflow_run.name }}

jobs:
  WriteLogs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name!='WriteLogs'}}

    steps:
      - uses: actions/checkout@v2

      - name: Output Job ID
        run: echo ${{ github.event.workflow_run.id }}

      - name: Send Workflow logs to Splunk
        if: ${{ always() }}
        uses: ./.github/actions/log_to_splunk
        with:
          splunk-url: http://34.213.134.166:8088/services/collector/raw #${{ secrets.HEC_URL }}
          hec-token: 903aca4b-9bc1-4c93-9147-6463d6f3a00b #${{ secrets.HEC_TOKEN }}
          github-token: ${{ secrets.API_TOKEN }}
          workflowID: ${{ env.triggerID }}
          source: ${{ env.triggerJob }}
